import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
       name: 'Jessica Clarice',
       email: 'HBIC@inCharge.org',
       password: bcrypt.hashSync('myPassword1234', 8),
       isAdmin: true
        },
        {
        name: 'SuperUSer',
        email: 'superUser@user.shop',
        password: bcrypt.hashSync('userPassWord1234', 8),
        isAdmin: false
        }

    ],

    albums: [
        {
            _id:'1077',
            ArtistID:'123496',
            artists:'Ween',
            AlbumTitle:'The Pod',
            Genre:'Psychedelic',
            copiesOnHand:'20',
            AlbumRelease:'1991-09-20 00:00:00',
            AlbumCost:'8',
            TrackAmount:'23',
            ProducerFName:'Dean and Gene',
            ProducerLName:'Ween',
            InPrint:true,
            image:'ThePod.jpeg',
            rating:'5.0',
            numReviews:'0'
        },
        {
            _id:'1177',
            ArtistID:'123456',
            artists:'Brian Eno',
            AlbumTitle:'Taking Tiger Mountain(By Strategy)',
            Genre:'Experimental',
            copiesOnHand:'15',
            AlbumRelease:'1974-11-01 00:00:00',
            AlbumCost:'9',
            TrackAmount:'10',
            ProducerFName:'Brian',
            ProducerLName:'Eno',
            InPrint:true,
            image:'TakingTigerMountain.jpg',
            rating:'5.0',
            numReviews:'6'
        },
        {
            _id:'1277',
            ArtistID:'123417',
            artists:'Frank Zappa',
            AlbumTitle:'Lumpy Gravy',
            Genre:'Experimental',
            copiesOnHand:'5',
            AlbumRelease:'1967-08-07 00:00:00',
            AlbumCost:'5',
            TrackAmount:'10',
            ProducerFName:'Frank',
            ProducerLName:'Zappa',
            InPrint:true,
            image:'LumpyGravy.jpg',
            rating:'3.5',
            numReviews:'0'
        },
        {
            _id:'1377',
            ArtistID:'123437',
            artists:'Patricia Taxxon',
            AlbumTitle:'Astral',
            Genre:'Ambient',
            copiesOnHand:'8',
            AlbumRelease:'2019-01-26 00:00:00',
            AlbumCost:'2',
            TrackAmount:'7',
            ProducerFName:'Patricia',
            ProducerLName:'Taxxon',
            InPrint:true,
            image:'Astral.jpg',
            rating:'1.0',
            numReviews:'0'
        },
        {
            _id:'1477',
            ArtistID:'123447',
            artists:'Syd Barrett',
            AlbumTitle:'Barrett',
            Genre:'Rock',
            copiesOnHand:'3',
            AlbumRelease:'1970-11-14 00:00:00',
            AlbumCost:'6',
            TrackAmount:'11',
            ProducerFName:'David',
            ProducerLName:'Gilmour',
            InPrint:false,
            image:'Barrett.jpg',
            rating:'5.0',
            numReviews:'0'
        },
        {
            _id:'1577',
            ArtistID:'123476',
            artists:'Miles Davis',
            AlbumTitle:'On the Corner',
            Genre:'Experimental',
            copiesOnHand:'18',
            AlbumRelease:'1972-10-11 00:00:00',
            AlbumCost:'10',
            TrackAmount:'4',
            ProducerFName:'Ted',
            ProducerLName:'Macero',
            InPrint:true,
            image:'OnTheCorner.jpg',
            rating:'4.0',
            numReviews:'0'
        },
        {
            _id:'1677',
            ArtistID:'123496',
            artists:'Ween',
            AlbumTitle:'Pure Guava',
            Genre:'Rock',
            copiesOnHand:'12',
            AlbumRelease:'1992-11-10 00:00:00',
            AlbumCost:'6',
            TrackAmount:'19',
            ProducerFName:'Dean and Gene',
            ProducerLName:'Ween',
            InPrint:true,
            image:'PureGuava.jpg',
            rating:'5.0',
            numReviews:'0'
        },
        {
            _id:'1777',
            ArtistID:'123427',
            artists:'Blur',
            AlbumTitle:'Think Tank',
            Genre:'Rock',
            copiesOnHand:'10',
            AlbumRelease:'2003-05-05 00:00:00',
            AlbumCost:'10',
            TrackAmount:'13',
            ProducerFName:'William',
            ProducerLName:'Orbit',
            InPrint:true,
            image:'ThinkTank.jpg',
            rating:'5.0',
            numReviews:'99'
        },
        {
            _id:'1778',
            ArtistID:'123437',
            artists:'Patricia Taxxon',
            AlbumTitle:'Cicada',
            Genre:'Ambient',
            copiesOnHand:'3',
            AlbumRelease:'2017-12-15 00:00:00',
            AlbumCost:'5',
            TrackAmount:'7',
            ProducerFName:'Patricia',
            ProducerLName:'Taxxon',
            InPrint:true,
            image:'Cicada.jpg',
            rating:'5.0',
            numReviews:'0'
        },
        {
            _id:'1877',
            ArtistID:'123486',
            artists:'King Gizzard and the Wizard Lizard',
            AlbumTitle:'Flying Microtonal Bananna',
            Genre:'Experimental',
            copiesOnHand:'3',
            AlbumRelease:'2017-02-24 00:00:00',
            AlbumCost:'5',
            TrackAmount:'9',
            ProducerFName:'Stu',
            ProducerLName:'Mackenzie',
            InPrint:true,
            image:'FlyingMicrotonalBanana.jpg',
            rating:'5.0',
            numReviews:'0'
        },
        {
            _id:'1977',
            ArtistID:'123466',
            artists:'David Bowie',
            AlbumTitle:'Station to Station',
            Genre:'Multi',
            copiesOnHand:'7',
            AlbumRelease:'1967-01-23 00:00:00',
            AlbumCost:'6',
            TrackAmount:'6',
            ProducerFName:'Harry',
            ProducerLName:'Maslin',
            InPrint:true,
            image:'StationToStation.jpg',
            rating:'5.0',
            numReviews:'33'
        },
        {
            _id:'2077',
            ArtistID:'123497',
            artists:'Bjork',
            AlbumTitle:'Debut',
            Genre:'Multi',
            copiesOnHand:'16',
            AlbumRelease:'1993-07-05 00:00:00',
            AlbumCost:'9',
            TrackAmount:'11',
            ProducerFName:'Nellee',
            ProducerLName:'Hooper',
            InPrint:true,
            image:'Debut.jpg',
            rating:'3.5',
            numReviews:'3'
        },
        {
            _id:'2177',
            ArtistID:'123497',
            artists:'Bjork',
            AlbumTitle:'Post',
            Genre:'Multi',
            copiesOnHand:'14',
            AlbumRelease:'1995-06-13 00:00:00',
            AlbumCost:'11',
            TrackAmount:'11',
            ProducerFName:'Bjork',
            ProducerLName:'Guðmundsdóttir',
            InPrint:true,
            image:'Post.png',
            rating:'4.5',
            numReviews:'0'
        },
        {
            _id:'2277',
            ArtistID:'123517',
            artists:'Kanye West',
            AlbumTitle:'Life of Pablo',
            Genre:'Hip Hop',
            copiesOnHand:'6',
            AlbumRelease:'2016-02-14 00:00:00',
            AlbumCost:'15',
            TrackAmount:'20',
            ProducerFName:'Kanye',
            ProducerLName:'West',
            InPrint:true,
            image:'LifeOfPablo.jpg',
            rating:'4.0',
            numReviews:'0'
        },
        {
            _id:'2377',
            ArtistID:'123517',
            artists:'Kanye West',
            AlbumTitle:'808s and Heartbreak',
            Genre:'Hip Hop',
            copiesOnHand:'0',
            AlbumRelease:'2008-11-24 00:00:00',
            AlbumCost:'13',
            TrackAmount:'12',
            ProducerFName:'Kanye',
            ProducerLName:'West',
            InPrint:true,
            image:'808sAndHeatbreak.jpg',
            rating:'3.5',
            numReviews:'0'
        },
        {
            _id:'2477',
            ArtistID:'123527',
            artists:'Pink Floyd',
            AlbumTitle:'Meddle',
            Genre:'Psychedelic',
            copiesOnHand:'18',
            AlbumRelease:'1971-10-31 00:00:00',
            AlbumCost:'4',
            TrackAmount:'6',
            ProducerFName:'Pink',
            ProducerLName:'Floyd',
            InPrint:true,
            image:'Meddle.jpg',
            rating:'4.0',
            numReviews:'0'
        },
        {
            _id:'2577',
            ArtistID:'123527',
            artists:'Pink Floyd',
            AlbumTitle:'Piper at the Gates of Dawn',
            Genre:'Psychedelic',
            copiesOnHand:'8',
            AlbumRelease:'1967-08-04 00:00:00',
            AlbumCost:'11',
            TrackAmount:'11',
            ProducerFName:'Norman',
            ProducerLName:'Smith',
            InPrint:true,
            image:'PiperAtTheGatesOfDawn.jpg',
            rating:'5.0',
            numReviews:'0'
        },
        {
            _id:'2677',
            ArtistID:'123537',
            artists:'Gorillaz',
            AlbumTitle:'Demon Days',
            Genre:'Multi',
            copiesOnHand:'4',
            AlbumRelease:'2005-05-15 00:00:00',
            AlbumCost:'7.99',
            TrackAmount:'16',
            ProducerFName:'Danger',
            ProducerLName:'Mouse',
            InPrint:true,
            image:'DemonDays.jpg',
            rating:'2.5',
            numReviews:'0'
        },
        {
            _id:'2777',
            ArtistID:'123537',
            artists:'Gorillaz',
            AlbumTitle:'D Sides',
            Genre:'Multi',
            copiesOnHand:'3',
            AlbumRelease:'2007-11-19 00:00:00',
            AlbumCost:'8.99',
            TrackAmount:'11',
            ProducerFName:'Danger',
            ProducerLName:'Mouse',
            InPrint:true,
            image:'D-sides.jpg',
            rating:'3.5',
            numReviews:'0'
        },
        {
            _id:'2778',
            ArtistID:'123417',
            artists:'Frank Zappa',
            AlbumTitle:'One Size Fits All',
            Genre:'Multi',
            copiesOnHand:'12',
            AlbumRelease:'1975-05-25 00:00:00',
            AlbumCost:'12',
            TrackAmount:'9',
            ProducerFName:'Frank',
            ProducerLName:'Zappa',
            InPrint:false,
            image:'OneSizeFitsAll.jpg',
            rating:'3.5',
            numReviews:'0'
        },
        {
            _id:'2877',
            ArtistID:'123547',
            artists:'Radiohead',
            AlbumTitle:'Ok Computer',
            Genre:'Experimental',
            copiesOnHand:'20',
            AlbumRelease:'1997-06-16 00:00:00',
            AlbumCost:'10.99',
            TrackAmount:'12',
            ProducerFName:'Nigel',
            ProducerLName:'Godrich',
            InPrint:true,
            image:'OkComputer.jpg',
            rating:'5.0',
            numReviews:'0'
        },
        {
            _id:'2977',
            ArtistID:'123547',
            artists:'Radiohead',
            AlbumTitle:'King of Limbs',
            Genre:'Country',
            copiesOnHand:'9',
            AlbumRelease:'2011-02-18 00:00:00',
            AlbumCost:'3.99',
            TrackAmount:'8',
            ProducerFName:'Nigel',
            ProducerLName:'Godrich',
            InPrint:false,
            image:'KingOfLimbs.jpg',
            rating:'4.5',
            numReviews:'0'
        },
        {
            _id:'3077',
            ArtistID:'123557',
            artists:'Todd Rundgren',
            AlbumTitle:'A Wizard, A True Star',
            Genre:'Rock',
            copiesOnHand:'2',
            AlbumRelease:'1973-03-02 00:00:00',
            AlbumCost:'7.99',
            TrackAmount:'19',
            ProducerFName:'Todd',
            ProducerLName:'Rundgren',
            InPrint:true,
            image:'AWizardATrueStar.jpg',
            rating:'5.0',
            numReviews:'0'
        },
        {
            _id:'3177',
            ArtistID:'123557',
            artists:'Todd Rundgren',
            AlbumTitle:'Faithful',
            Genre:'Rock',
            copiesOnHand:'5',
            AlbumRelease:'1976-04-01 00:00:00',
            AlbumCost:'13.99',
            TrackAmount:'12',
            ProducerFName:'Todd',
            ProducerLName:'Rundgren',
            InPrint:true,
            image:'Faithful.jpg',
            rating:'3.0',
            numReviews:'0'
        },
        {
            _id:'3277',
            ArtistID:'123567',
            artists:'Roxy Music',
            AlbumTitle:'Roxy Music',
            Genre:'Experimental',
            copiesOnHand:'1',
            AlbumRelease:'1972-06-16 00:00:00',
            AlbumCost:'7.99',
            TrackAmount:'9',
            ProducerFName:'Roxy',
            ProducerLName:'Music',
            InPrint:true,
            image:'RoxyMusic.jpg',
            rating:'5.0',
            numReviews:'0'
        },
        {
            _id:'3377',
            ArtistID:'123567',
            artists:'Roxy Music',
            AlbumTitle:'For Your Pleasure',
            Genre:'Experimental',
            copiesOnHand:'4',
            AlbumRelease:'1972-03-23 00:00:00',
            AlbumCost:'12.99',
            TrackAmount:'8',
            ProducerFName:'Roxy',
            ProducerLName:'Music',
            InPrint:true,
            image:'ForYourPleasure.jpg',
            rating:'4.0',
            numReviews:'0'
        },
        {
            _id:'3477',
            ArtistID:'123577',
            artists:'Scott Walker',
            AlbumTitle:'Scott 4',
            Genre:'Soul',
            copiesOnHand:'7',
            AlbumRelease:'1969-11-01 00:00:00',
            AlbumCost:'4.99',
            TrackAmount:'10',
            ProducerFName:'John',
            ProducerLName:'Franz',
            InPrint:true,
            image:'Scott4.jpg',
            rating:'4.0',
            numReviews:'12'
        },
        {
            _id:'3577',
            ArtistID:'123577',
            artists:'Scott Walker',
            AlbumTitle:'Nite Flights',
            Genre:'Experimental',
            copiesOnHand:'0',
            AlbumRelease:'1978-07-01 00:00:00',
            AlbumCost:'12.99',
            TrackAmount:'10',
            ProducerFName:'Scott',
            ProducerLName:'Walker',
            InPrint:true,
            image:'NiteFlights.jpeg',
            rating:'2.5',
            numReviews:'0'
        },
        {
            _id:'3677',
            ArtistID:'123587',
            artists:'Can',
            AlbumTitle:'Tago Mago',
            Genre:'Experimental',
            copiesOnHand:'0',
            AlbumRelease:'1971-02-01 00:00:00',
            AlbumCost:'6.99',
            TrackAmount:'7',
            ProducerFName:'The band',
            ProducerLName:'CAN',
            InPrint:true,
            image:'TagoMago.jpg',
            rating:'2.5',
            numReviews:'12'
        },
        {
            _id:'3777',
            ArtistID:'123587',
            artists:'Can',
            AlbumTitle:'Ege Bamyasi',
            Genre:'Experimental',
            copiesOnHand:'14',
            AlbumRelease:'1972-11-01 00:00:00',
            AlbumCost:'11.99',
            TrackAmount:'7',
            ProducerFName:'The band',
            ProducerLName:'CAN',
            InPrint:true,
            image:'EgeBamyasi.jpg',
            rating:'3.5',
            numReviews:'2'
        },
        {
            _id:'3778',
            ArtistID:'123427',
            artists:'Blur',
            AlbumTitle:'13',
            Genre:'Rock',
            copiesOnHand:'19',
            AlbumRelease:'1999-03-15 00:00:00',
            AlbumCost:'19.99',
            TrackAmount:'13',
            ProducerFName:'William',
            ProducerLName:'Orbit',
            InPrint:true,
            image:'13.jpg',
            rating:'4.0',
            numReviews:'3'
        },
        {
            _id:'3877',
            ArtistID:'123597',
            artists:'The Talking Heads',
            AlbumTitle:'Fear of Music',
            Genre:'Funk',
            copiesOnHand:'16',
            AlbumRelease:'1979-08-03 00:00:00',
            AlbumCost:'5.99',
            TrackAmount:'11',
            ProducerFName:'Brian',
            ProducerLName:'Eno',
            InPrint:true,
            image:'FearofMusic.jpg',
            rating:'3.5',
            numReviews:'0'
        },
        {
            _id:'3977',
            ArtistID:'123597',
            artists:'The Talking Heads',
            AlbumTitle:'Remain in Light',
            Genre:'Experimental',
            copiesOnHand:'11',
            AlbumRelease:'1980-10-08 00:00:00',
            AlbumCost:'11',
            TrackAmount:'8',
            ProducerFName:'Brian',
            ProducerLName:'Eno',
            InPrint:true,
            image:'RemainInLight.jpg',
            rating:'2.5',
            numReviews:'0'
        },
        {
            _id:'4077',
            ArtistID:'123617',
            artists:'Janes Addiction',
            AlbumTitle:'Nothings Shocking',
            Genre:'Rock',
            copiesOnHand:'4',
            AlbumRelease:'1988-08-23 00:00:00',
            AlbumCost:'7.99',
            TrackAmount:'11',
            ProducerFName:'Dave',
            ProducerLName:'Jerden',
            InPrint:true,
            image:'NothingsShocking.jpg',
            rating:'3.5',
            numReviews:'0'
        },
        {
            _id:'4177',
            ArtistID:'123617',
            artists:'Janes Addiction',
            AlbumTitle:'Ritual de la Habitual',
            Genre:'Rock',
            copiesOnHand:'16',
            AlbumRelease:'1990-08-21 00:00:00',
            AlbumCost:'10.99',
            TrackAmount:'9',
            ProducerFName:'Dave',
            ProducerLName:'Jerden',
            InPrint:true,
            image:'RitualDeLaHabitual.jfif',
            rating:'2.5',
            numReviews:'0'
        },
        {
            _id:'4778',
            ArtistID:'123437',
            artists:'Show is the Rainbow',
            AlbumTitle:'Aw Nutz',
            Genre:'Experimental',
            copiesOnHand:'9',
            AlbumRelease:'2018-03-03 00:00:00',
            AlbumCost:'8',
            TrackAmount:'9',
            ProducerFName:'Darren',
            ProducerLName:'Keen',
            InPrint:false,
            image:'AwNutz.jpg',
            rating:'5.0',
            numReviews:'0'
        },
        {
            _id:'5778',
            ArtistID:'123447',
            artists:'Syd Barrett',
            AlbumTitle:'The Madcap Laughs',
            Genre:'Psychedelic',
            copiesOnHand:'11',
            AlbumRelease:'1970-01-03 00:00:00',
            AlbumCost:'9',
            TrackAmount:'13',
            ProducerFName:'David',
            ProducerLName:'Gilmour',
            InPrint:true,
            image:'MadcapLaughs.jpg',
            rating:'5.0',
            numReviews:'0'
        },
        {
            _id:'6778',
            ArtistID:'123456',
            artists:'Brian Eno',
            AlbumTitle:'Another Green World',
            Genre:'Experimental',
            copiesOnHand:'20',
            AlbumRelease:'1975-09-01 00:00:00',
            AlbumCost:'10',
            TrackAmount:'14',
            ProducerFName:'Brian',
            ProducerLName:'Eno',
            InPrint:true,
            image:'AnotherGreenWorld.jpg',
            rating:'3.5',
            numReviews:'44'
        },
        {
            _id:'7778',
            ArtistID:'123466',
            artists:'David Bowie',
            AlbumTitle:'Low',
            Genre:'Rock',
            copiesOnHand:'11',
            AlbumRelease:'1977-01-14 00:00:00',
            AlbumCost:'10',
            TrackAmount:'0',
            ProducerFName:'Tony',
            ProducerLName:'Visconti',
            InPrint:true,
            image:'Low.jpg',
            rating:'5.0',
            numReviews:'2'
        },
        {
            _id:'8778',
            ArtistID:'123476',
            artists:'Miles Davis',
            AlbumTitle:'Bitches Brew',
            Genre:'Jazz',
            copiesOnHand:'17',
            AlbumRelease:'1970-03-30 00:00:00',
            AlbumCost:'10',
            TrackAmount:'6',
            ProducerFName:'Teo',
            ProducerLName:'Macero',
            InPrint:true,
            image:'BitchesBrew.jpg',
            rating:'4.0',
            numReviews:'5'
        },
        {
            _id:'9778',
            ArtistID:'123486',
            artists:'King Gizzard and the Wizard Lizard',
            AlbumTitle:'Nonagon Infinity',
            Genre:'Rock',
            copiesOnHand:'13',
            AlbumRelease:'2016-04-29 00:00:00',
            AlbumCost:'15',
            TrackAmount:'9',
            ProducerFName:'Wayne',
            ProducerLName:'Gordon',
            InPrint:true,
            image:'NonagonInfinity.jpg',
            rating:'3.0',
            numReviews:'4'
        },

    ],
};

export default data;
